language: node_js
script: chmod +x ./release.sh && ./release.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: release
  repo: photospice/photospice.github.io
  target_branch: master
  on:
    branch: master
